#ifndef MESSAGE_H
#define MESSAGE_H

enum Type {
	MOVE_FORWARD_MESSAGE,
	MOVE_BACKWARD_MESSAGE,
	TURN_LEFT_MESSAGE,
	TURN_RIGHT_MESSAGE,
	MOVE_FORWARD_BY_MESSAGE,
	MOVE_BACKWARD_BY_MESSAGE,
	TURN_LEFT_BY_MESSAGE,
	TURN_RIGHT_BY_MESSAGE,
	STOP_MESSAGE,
	PRINT_MESSAGE,
	SPEED_MESSAGE,
	JOYSTICK_MESSAGE,
	ENCODER_DATA_MESSAGE,
	LOCATOR_DATA_MESSAGE
};

struct Message {
	byte type;
	int payloadA;
	int payloadB;
};

#endif